#!/bin/bash
production_branch='master'
staging_branch='staging'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color


print() {
    echo -e "$2$1${NC}"
}

if [[ $current_branch != "$production_branch" && $current_branch != "$staging_branch" ]] ; then
    exit 0
fi

cp -r hooks/ .git/
cp -r scripts/ .git/hooks/

exit 0